### ISSUE TITLE
Test failure in 0.7.0.0

### ISSUE THREAD

**Issue by bergmark** [joneshf/servant-ruby#3]
```
### Failure in src/Servant/Ruby.hs:324: expression `\str -> snake (snake $ T.pack str) == snake (T.pack str)'
*** Failed! Falsifiable (after 18 tests and 5 shrinks):
"A\119985"
```

**Comment by joneshf** [comment]
Fun fun. Thanks for the report! Will look into it.

**Comment by joneshf** [comment]
Looks like it's [something upstream](https://bitbucket.org/tdammers/casing/issues/2). If it ends up being something essential to the library, probably will document it, and change/remove the test. Otherwise will figure a fix for it.
